### ISSUE TITLE
Failure during moodle install if settings exist

### ISSUE THREAD

**Issue by aolley** [darrencocco/moodle-local_advancedconfig#1]
https://github.com/darrencocco/moodle-local_advancedconfig/blob/54683e47609d1a13aebf74bb3fdb0ab905464772/classes/helper/admin_setting_redirector.php#L90

This call to the cache fails during install (or whenever CACHE_DISABLE_ALL) is set. It looks a check for cache_disabled is needed here as well - otherwise the cache just gives back `false`, which trips an exception on the next line.

**Comment by darrencocco** [comment]
push a fix to master, only short term solution
